name:	Docker CI/CD file

on:
  push:
   branches:  [ "main" ]

jobs:
  build_and_push_docker_job:
    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Checkout Repository Source Code
      uses: actions/checkout@v4
    - name: Step 2 - Authenticate and Login to Azure container registry
      uses: azure/docker-login@v1
      with:
        login-server: mahaazr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: Step 3 - Build Docker Image and Push to ACR
      run: | 
        docker build -t  mahaazr.azurecr.io/my-custom-app:v1
        docker push mahaazr.azurecr.io/my-custom-app:v1

